version: '3'

services:
  mongodb-server:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: customer1   
    volumes:
      - mongo-data:/data/db   
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongodb-server

  postgres-compose:
    image: postgres   
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: dbescola
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 110196
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4 
    container_name: postgres-adminpg4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: robeto@altsys.com.br
      PGADMIN_DEFAULT_PASSWORD: 110196
    ports:
      - "16543:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
    links:
      - "postgres-compose:pgsql-sever"

networks: 
  postgres-compose-network:
    driver: bridge

volumes:
  mongo-data:
  postgres-data:

